### PR TITLE
Cosmetic fixes

### PR DESCRIPTION
**Pull request by thias**
* Remove useless files (.DS_Store, config.yaml)
* Fix Makefile indentation
* REAME typos and structure changes, fix PHP short open tag

### CODE REVIEW

**Review by vmsachin — COMMENTED** [review]
I have made these fixes for 0.2.0 release. Thank you!

**Comment by thias** [comment]
Clearly not all of them, as the Makefile is still a mix of spaces and tabs and the README is pretty much the same, with _extesnion_, the super-obsolete PHP short open tag and all. Do you want me to quickly rebase all of these minor cosmetic enhancements?

**Comment by vmsachin** [comment]
sure, can you rebase the changes, ill merge them

**Comment by thias** [comment]
I've updated the README changes, keeping them minimal. I didn't touch the Makefile this time.

Would a more intrusive PR ripping out composer support and providing more generic build+install instructions be accepted? After seeing #12 it looks like most people seem to agree that there is no need to try and do too much, especially through fragile checks and potentially wrong assumptions, and that the extension's target audience knows what to do with a php module file.

**Comment by PixiBixi** [comment]
I would like to add something, Aerospike is not a common software used by anyone

When you need a soft like it, you have specific requirements and you perfectly know your infrastructure, there's no need to install it on the correct folder or whatever, just build it :)

**Review by vmsachin — APPROVED** [review]

**Comment by vmsachin** [comment]
@thias Sure, you can make a PR for the a better build process. Even we are looking into bettering the build for the php client. Any help in this area would be appreciated. Thanks!

**Pull request merged**
